/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LexiconRouteImport } from './routes/lexicon'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AuthorsIndexRouteImport } from './routes/authors.index'
import { Route as AuthorsIdRouteImport } from './routes/authors.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as SurahIdRouteImport } from './routes/surah.$id'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as ApiPublicRecitationSurahAyahRouteImport } from './routes/api/public/recitation.$surah.$ayah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiconRoute = LexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIdRoute = AuthorsIdRouteImport.update({
  id: '/authors/$id',
  path: '/authors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIdRoute = SurahIdRouteImport.update({
  id: '/surah/$id',
  path: '/surah/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecitationSurahAyahRoute =
  ApiPublicRecitationSurahAyahRouteImport.update({
    id: '/api/public/recitation/$surah/$ayah',
    path: '/api/public/recitation/$surah/$ayah',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/lexicon': typeof LexiconRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$id': typeof AuthorsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/recitation/$surah/$ayah': typeof ApiPublicRecitationSurahAyahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/lexicon': typeof LexiconRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$id': typeof AuthorsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/recitation/$surah/$ayah': typeof ApiPublicRecitationSurahAyahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/lexicon': typeof LexiconRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$id': typeof AuthorsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/surah/$id': typeof SurahIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/recitation/$surah/$ayah': typeof ApiPublicRecitationSurahAyahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/lexicon'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/authors/$id'
    | '/p/$slug'
    | '/surah/$id'
    | '/articles/'
    | '/authors/'
    | '/api/public/contact'
    | '/api/public/tts'
    | '/api/public/recitation/$surah/$ayah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/lexicon'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/authors/$id'
    | '/p/$slug'
    | '/surah/$id'
    | '/articles'
    | '/authors'
    | '/api/public/contact'
    | '/api/public/tts'
    | '/api/public/recitation/$surah/$ayah'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/lexicon'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/authors/$id'
    | '/p/$slug'
    | '/surah/$id'
    | '/articles/'
    | '/authors/'
    | '/api/public/contact'
    | '/api/public/tts'
    | '/api/public/recitation/$surah/$ayah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  LexiconRoute: typeof LexiconRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  AuthorsIdRoute: typeof AuthorsIdRoute
  PSlugRoute: typeof PSlugRoute
  SurahIdRoute: typeof SurahIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  ApiPublicRecitationSurahAyahRoute: typeof ApiPublicRecitationSurahAyahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexicon': {
      id: '/lexicon'
      path: '/lexicon'
      fullPath: '/lexicon'
      preLoaderRoute: typeof LexiconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$id': {
      id: '/authors/$id'
      path: '/authors/$id'
      fullPath: '/authors/$id'
      preLoaderRoute: typeof AuthorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$id': {
      id: '/surah/$id'
      path: '/surah/$id'
      fullPath: '/surah/$id'
      preLoaderRoute: typeof SurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recitation/$surah/$ayah': {
      id: '/api/public/recitation/$surah/$ayah'
      path: '/api/public/recitation/$surah/$ayah'
      fullPath: '/api/public/recitation/$surah/$ayah'
      preLoaderRoute: typeof ApiPublicRecitationSurahAyahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  LexiconRoute: LexiconRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  AuthorsIdRoute: AuthorsIdRoute,
  PSlugRoute: PSlugRoute,
  SurahIdRoute: SurahIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  ApiPublicRecitationSurahAyahRoute: ApiPublicRecitationSurahAyahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
